### ISSUE TITLE
Binary Literals, Underscores in Literals SIP/SLIP tracking

### ISSUE THREAD

**Issue by dickwall** [scala/slip#8]
https://groups.google.com/forum/#!msg/scala-debate/4-CE9Lpf6CM/UJrhS9cyYcgJ

https://www.reddit.com/r/scala/comments/3aqlhu/is_there_a_voting_mechanism_for_new_scala_features/

https://github.com/non/spire#syntax

Need a volunteer to reach out to Eran Medan and find out current interest/commitment.

Some possibility that this could be satisfied with a spire-like approach to literals using string interp in a library -> SLIP proposal.

**Comment by SethTisue** [comment]
this was discussed on scala-internals in May 2016: https://groups.google.com/d/msg/scala-internals/ONkqLTxw4mM/Ru3TX9DABwAJ

**Comment by aishfenton** [comment]
And after much reflection. I still think some form of thousand-separator is needed. I use spire's i"100 000" on some projects, and it works great. But I really don't want to add Spire as a dependency just to get this functionality.

**Comment by SethTisue** [comment]
I wonder if the Spire folks would want to provide it as a standalone module?

**Comment by SethTisue** [comment]
Closing since this repo is being decommissioned. This could still go forward as either a SIP or under the new Scala Platform Proposal (http://www.scala-lang.org/blog/2016/11/28/spp.html), depending on whether it ends up as language support or just as a library (or standard module or addition to the standard library).
